name: text_in_image_detector
description: A flutter example project, to detect text in an image and translate it afterwards.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_ml_kit: ^0.7.3
  image_picker: ^0.8.5
  learning_translate: ^0.0.4
  #translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true